services:
  db:
    image: postgres:15
    container_name: rykerwiki-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: rykerwiki
      POSTGRES_USER: rykerwikijs
      POSTGRES_PASSWORD: rykerwikijs
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2
    container_name: rykerwikijs
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "8080:3000"
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: rykerwikijs
      DB_PASS: rykerwikijs
      DB_NAME: rykerwiki

    develop:
      watch:
        - action: sync
          path: ./content
          target: /wiki/content

volumes:
  db-data: